sources:
  main: src/main.cpp
  target: src/target.cpp
  target_h: src/target.h

commands:
  install: conan install . -s build_type=Release -of ./build
  build: conan build . -of ./build
  run: ./build/test

